### ISSUE TITLE
Incorrectly eaten value

### ISSUE THREAD

**Issue by b-ryan** [syntax-tree/mdast#11]
I'm using [doctoc](https://github.com/thlorenz/doctoc) to generate a table of contents for my readme. I received this error:

```
DocToccing single file "README.md" for github.com.

==================


/home/buck/src/RJMetrics/connections-service/node_modules/doctoc/node_modules/markdown-to-ast/node_modules/mdast/node_modules/vfile/index.js:541
        throw err;
              ^
74:11: Incorrectly eaten value: please report this warning on http://git.io/vUYWz
```

I tracked it down to the way a table was formatted:

```
| |God|Admin|Standard|
|---|---|---|---|
|GET|x|x| |
|PUT|x|x| |
|POST|x|x| |
```

It seems to not like the empty table values. Upon changing it to

```
| |God|Admin|Standard|
|---|---|---|---|
|GET|x|x|-|
|PUT|x|x|-|
|POST|x|x|-|
```

the error is gone

**Comment by wooorm** [comment]
Thanks for mentioning, however, the problem is doctoc, as it’s using an old version of mdast (renamed to remark). See https://github.com/thlorenz/doctoc/issues/94 for more information.

**Comment by b-ryan** [comment]
thanks :+1:
