### ISSUE TITLE
Incorrectly eaten value

### ISSUE THREAD

**Issue by billtorcaso** [syntax-tree/mdast#12]
Sorry I can't give you more detail...

 $ doctoc README.md 

DocToccing single file "README.md" for github.com.
# 

/usr/local/lib/node_modules/doctoc/node_modules/vfile/index.js:541
        throw err;
        ^
12:22: Incorrectly eaten value: please report this warning on http://git.io/vUYWz

**Comment by wooorm** [comment]
Thanks for mentioning, however, the problem is doctoc, as it’s using an old version of mdast (renamed to remark). See https://github.com/thlorenz/doctoc/issues/94 for more information.
