### ISSUE TITLE
Add a `target` on `Link` nodes

### ISSUE THREAD

**Issue by cedricdelpoux** [syntax-tree/mdast#14]
I would like to add a target attr on a `Link` object to handle `target="_blank"` case : 
```
interface Link <: Parent {
  type: "link";
  title: string | null;
  url: string;
  target: string;
}
```

Is it possible ?

**Comment by wooorm** [comment]
Well, this is two-sided:

* It’s possible to add new, unknown properties to nodes, that’s fine
* I don’t think this should be in mdast (or remark) though, as `target` isn’t a standard thing in markdown

Maybe [hast](https://github.com/syntax-tree/hast) is what you want?
