### ISSUE TITLE
Add support for `DefinitionList` nodes

### ISSUE THREAD

**Issue by micha149** [syntax-tree/mdast#15]
Hey there!

As I created some ASTs in the *mdast* format, I came across definition lists and noticed that they are currently not specified for mdast. Is there any reason to not specify them? I know they are not part of common mark, but tables aren't too.

I would like offer a pull request with a specification for definition list…

**Comment by wooorm** [comment]
Definition lists are not part of any mayor markdown flavour, commonmark or gfm, so they’re not specified here.
You can of course feel free to specify them in your own extensions, and we can link to that here, but they shouldn’t be a default.

**Comment by wooorm** [comment]
I’m closing this as I think it shouldn’t be in core!
