### ISSUE TITLE
push npm code to github

### ISSUE THREAD

**Issue by dominictarr** [syntax-tree/mdast#2]
according to the npm site, there have been 81 releases of mdast but I can only see 3 commits here.
Is this the official repo?

**Comment by wooorm** [comment]
mdast was renamed to remark, read more about it here: https://github.com/wooorm/remark/releases/tag/3.0.0 (sorry, missed this issue)

**Comment by wooorm** [comment]
Excuse my short reply, I was on my phone. The link should tell you everything you’d want to know, if not, either reply here or send me an e-mail.

Also: there’s some back story [here](https://github.com/wooorm/remark/issues/113).

**Comment by dominictarr** [comment]
okay thanks, I see it now in the readme. I missed that earlier because I
was in rush because of the vfile install problem

**Comment by wooorm** [comment]
Ha, I can imagine, don’t worry :)
