### ISSUE TITLE
What content models are allowed?

### ISSUE THREAD

**Issue by tolmasky** [syntax-tree/mdast#21]
Is there anywhere that defines what children are allowed in what nodes?

**Comment by wooorm** [comment]
Nope, but I think that there should be!
Why are you pondering this question?

**Comment by tolmasky** [comment]
I'm doing some post-processing for a program that uses .md for a file format, and I just don't really feel like I have a handle as to whether I'm actually handling all the possible combinations. Do I worry about arbitrary markup in tables? Is this something that isn't necessarily possible the written markdown form but still allowed in the syntax nodes? etc.

**Comment by wooorm** [comment]
Hmm, interesting. What is and isn’t allowed depends on the node. I think it would make sense to document this. HTML does it as well.
We made a little project [mdast-util-phrasing](https://github.com/syntax-tree/mdast-util-phrasing/blob/master/index.js) that documents what’s allowed to be in paragraphs (and table cells, for that matter).
I think it’s a good addition, would you like to work on it?
