### ISSUE TITLE
Add support for `meta` field on `Code` blocks

### ISSUE THREAD

**Issue by Heziode** [syntax-tree/mdast#26]
In the section [code](https://github.com/syntax-tree/mdast#code) in the README we have the following example:

    ```javascript highlight-line="2"
    foo()
    bar()
    baz()
    ```

**Expected**: it should give something like this:
```js
{
  type: 'code',
  lang: 'javascript',
  meta: 'highlight-line="2"',
  value: 'foo()\nbar()\nbaz()'
}
```

**Actual**: we take this instead:
```js
{
  type: 'code',
  lang: 'javascript highlight-line="2"',
  value: 'foo()\nbar()\nbaz()'
}
```

**Comment by wooorm** [comment]
I think you‘re talking about remark, the parser that creates mdast, right?
In that case, I merged the [PR for this today](https://github.com/remarkjs/remark/pull/345). It’ll be released soon with the new changes.

**Comment by Heziode** [comment]
> I think you‘re talking about remark, the parser that creates mdast, right?

Yes, I just realized…

> In that case, I merged the PR for this today. It’ll be released soon with the new changes.

Great, this can maybe unlock zestedesavoir/zmarkdown#255
