### ISSUE TITLE
Add support for shortcode blocks

### ISSUE THREAD

**Issue by alexandernanberg** [syntax-tree/mdast#27]
Apologies if this is posted in the wrong place, might belong to the `ideas` repo instead? I can move it in that case.

I'd really love to see shortcode parsing built-in. That would open up a lot of doors especially when working with Gatsby etc. I think the way Hugo handles it is pretty nice https://gohugo.io/content-management/shortcodes/

**Comment by ChristianMurphy** [comment]
Hey @alexandernanberg! :wave: 
mdast/remark generally stick to [CommonMark](https://spec.commonmark.org/0.28/) for features included in core, and keep syntax extensions that are above and beyond CommonMark as [remark plugins](https://github.com/remarkjs/remark/blob/master/doc/plugins.md).

Shortcodes would be included in the above and beyond.
That being said, several flavors of shortcodes are available for remark today via plugins.

#### [remark-shortcodes](https://github.com/djm/remark-shortcodes)

```md
The example below uses the default start & end blocks that
this parser ships with:

[[ MailchimpForm id="chfk2" ]]

But they are configurable, so if you're coming from Hugo say,
you can set them as such:

{{< MailchimpForm id="chfk2" >}}
```

#### [remark-macro](https://github.com/dimerapp/remark-macro)

```md
# Hello

Writing some markdown

[alert]
This is an alert message
[/alert]
```

#### [mdx](https://github.com/mdx-js/mdx)

```mdx
import { Chart } from '../components/chart'

# Here’s a chart

The chart is rendered inside our MDX document.

<Chart />
```
