### ISSUE TITLE
Rename `depth` to `rank`

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/mdast#31]
### Subject of the feature

Rank is the term used by HTML. Depth alludes a bit to nesting, which is not the case.

**Comment by vnphanquang** [comment]
I agree. Using `rank` will be consistent with [HTML 5.2 specs](https://www.w3.org/TR/html52/sections.html#the-h1-h2-h3-h4-h5-and-h6-elements) as well.

**Comment by wooorm** [comment]
Yup! 👍

(edit: I misread your comment)

**Comment by wooorm** [comment]
Closing for now. It isn’t perfect. At some point it can be improved. For now, it might just wrak havoc...
