### ISSUE TITLE
mdast@latest (3.0.0) npm package contains no code

### ISSUE THREAD

**Issue by zeke** [syntax-tree/mdast#38]
Hi @wooorm!

I'm trying to use the `mdast` package with `npm install mdast`. It appears that this package used to be an actual implementation of the parser, but now I'm just seeing the spec document for version 3.0.0:

<img width="956" alt="Screen Shot 2021-02-27 at 5 00 21 PM" src="https://user-images.githubusercontent.com/2289/109404697-5ad73d80-791d-11eb-9d89-8badef6dc830.png">

https://unpkg.com/browse/mdast@3.0.0/

Is this intended?

**Comment by ChristianMurphy** [comment]
@wooorm may be able to comment more on the intent, but I believe the docs are the intent from https://github.com/syntax-tree/unist/discussions/32.
The parser now lives at https://github.com/syntax-tree/mdast-util-from-markdown for the AST.
Or https://github.com/micromark/micromark or you want tokens, or don't need mdast transforms.

**Comment by zeke** [comment]
Thanks for the context @ChristianMurphy that's helpful.

Might be good to `npm deprecate` the `mdast` package so folks get a clarifying message when installing it.

**Comment by wooorm** [comment]
@zeke It *is* deprecated?

**Comment by wooorm** [comment]
It’s been 5 years since I pushed a major version, without code, and deprecated it.
First pushing a major and then deprecating that is IMO a better experience, because folks will notice there’s a major when they’re ready to update, and *then* see that message pop up.

I’m guessing though, as it’s been 5 years since it’s been deprecated, that you’re on an old project and seeing *a ton* of deprecation message, so maybe missed this one?

**Comment by zeke** [comment]
Are you sure? I don't see a deprecation message:

```
$ mkdir mdast-test && cd mdast-test
$ echo "{}" > package.json
$ npm i mdast

npm WARN deprecated mdast@3.0.0: `mdast` was renamed to `remark`
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN mdast-test No description
npm WARN mdast-test No repository field.
npm WARN mdast-test No license field.

+ mdast@3.0.0
added 1 package from 1 contributor and audited 1 package in 0.645s
found 0 vulnerabilities
```

**Comment by ChristianMurphy** [comment]
```
npm WARN deprecated mdast@3.0.0: `mdast` was renamed to `remark`
```

looks like a deprecation notice to me?

**Comment by zeke** [comment]
Doh! Ignore me. 🙈

**Comment by Spaperonzolo** [comment]
Sorry but i no speack very well English

Il mar 2 mar 2021, 19:01 Zeke Sikelianos <notifications@github.com> ha
scritto:
