### ISSUE TITLE
Replace link’s `href` and image’s `src` with unified `url` property

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/mdast#8]
It seems quite unnecessary to use different properties for a such a similar thing. One `url` is cleaner and simpler.

**Comment by wooorm** [comment]
@eush77 Sorry for all the pings, I just value your brain / input on this :)

**Comment by eush77** [comment]
:+1: I like this. Consistency is a good thing, and in my opinion HTML terminology is not really applicable here.

**Comment by wooorm** [comment]
Hmm, [`definition` uses `link`](https://github.com/wooorm/mdast#definition). Should that be changed to `url` too, or should we use `link` everywhere? (I prefer `url` more as it’s more correct, `link` is a bit weird for images)

**Comment by eush77** [comment]
I agree, `url` is a better term.

**Comment by wooorm** [comment]
Closed by 94fd6d4.
